#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPFilterColumn.h"
#import "ASPLink.h"
#import "ASPDataSorter.h"


@protocol ASPAutoFilter
@end

@interface ASPAutoFilter : ASPObject


@property(nonatomic) NSArray<ASPFilterColumn>* filterColumns;

@property(nonatomic) NSString* range;

@property(nonatomic) ASPDataSorter* sorter;

@property(nonatomic) ASPLink* link;

@end
