#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPAutoFitterOptions
@end

@interface ASPAutoFitterOptions : ASPObject


@property(nonatomic) NSNumber* autoFitMergedCells;

@property(nonatomic) NSNumber* ignoreHidden;

@property(nonatomic) NSNumber* onlyAuto;

@end
