#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPLink.h"


@protocol ASPComment
@end

@interface ASPComment : ASPObject


@property(nonatomic) NSString* cellName;

@property(nonatomic) NSString* author;

@property(nonatomic) NSString* htmlNote;

@property(nonatomic) NSString* note;

@property(nonatomic) NSNumber* autoSize;

@property(nonatomic) NSNumber* isVisible;

@property(nonatomic) NSNumber* width;

@property(nonatomic) NSNumber* height;

@property(nonatomic) NSString* textHorizontalAlignment;

@property(nonatomic) NSString* textOrientationType;

@property(nonatomic) NSString* textVerticalAlignment;

@property(nonatomic) ASPLink* link;

@end
