#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPCreatePivotTableRequest
@end

@interface ASPCreatePivotTableRequest : ASPObject


@property(nonatomic) NSString* name;

@property(nonatomic) NSString* sourceData;

@property(nonatomic) NSString* destCellName;

@property(nonatomic) NSNumber* useSameSource;

@property(nonatomic) NSArray* /* NSNumber */ pivotFieldRows;

@property(nonatomic) NSArray* /* NSNumber */ pivotFieldColumns;

@property(nonatomic) NSArray* /* NSNumber */ pivotFieldData;

@end
