#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPLink.h"
#import "ASPLinkElement.h"


@protocol ASPCells
@end

@interface ASPCells : ASPObject


@property(nonatomic) NSNumber* maxRow;

@property(nonatomic) NSNumber* maxColumn;

@property(nonatomic) NSNumber* cellCount;

@property(nonatomic) ASPLinkElement* rows;

@property(nonatomic) ASPLinkElement* columns;

@property(nonatomic) NSArray<ASPLinkElement>* cellList;

@property(nonatomic) ASPLink* link;

@end
