#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPSortKey.h"


@protocol ASPDataSorter
@end

@interface ASPDataSorter : ASPObject


@property(nonatomic) NSNumber* caseSensitive;

@property(nonatomic) NSNumber* hasHeaders;

@property(nonatomic) NSArray<ASPSortKey>* keyList;

@property(nonatomic) NSNumber* sortLeftToRight;

@end
