#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPDrawingTilePicOption.h"
#import "ASPLinkElement.h"
#import "ASPDrawingPicFormatOption.h"


@protocol ASPDrawingTextureFill
@end

@interface ASPDrawingTextureFill : ASPObject


@property(nonatomic) NSString* type;

@property(nonatomic) NSNumber* transparency;

@property(nonatomic) NSNumber* scale;

@property(nonatomic) ASPDrawingTilePicOption* tilePicOption;

@property(nonatomic) ASPDrawingPicFormatOption* picFormatOption;

@property(nonatomic) ASPLinkElement* image;

@end
