#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPCustomFilter.h"
#import "ASPDynamicFilter.h"
#import "ASPTop10Filter.h"
#import "ASPIconFilter.h"
#import "ASPColorFilter.h"
#import "ASPMultipleFilters.h"


@protocol ASPFilterColumn
@end

@interface ASPFilterColumn : ASPObject


@property(nonatomic) NSNumber* fieldIndex;

@property(nonatomic) NSString* filterType;

@property(nonatomic) ASPMultipleFilters* multipleFilters;

@property(nonatomic) ASPColorFilter* colorFilter;

@property(nonatomic) NSArray<ASPCustomFilter>* customFilters;

@property(nonatomic) ASPDynamicFilter* dynamicFilter;

@property(nonatomic) ASPIconFilter* iconFilter;

@property(nonatomic) ASPTop10Filter* top10Filter;

@property(nonatomic) NSString* visibledropdown;

@end
