#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPDrawingOleObject.h"


@protocol ASPOleObjectResponse
@end

@interface ASPOleObjectResponse : ASPObject


@property(nonatomic) ASPDrawingOleObject* oleObject;

@property(nonatomic) NSString* code;

@property(nonatomic) NSString* status;

@end
