#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPPivotPivotField.h"
#import "ASPLink.h"
#import "ASPPivotPivotFilter.h"
#import "ASPCellArea.h"


@protocol ASPPivotPivotTable
@end

@interface ASPPivotPivotTable : ASPObject


@property(nonatomic) NSString* altTextDescription;

@property(nonatomic) NSString* altTextTitle;

@property(nonatomic) NSString* autoFormatType;

@property(nonatomic) NSArray<ASPPivotPivotField>* baseFields;

@property(nonatomic) NSArray<ASPPivotPivotField>* columnFields;

@property(nonatomic) NSNumber* columnGrand;

@property(nonatomic) NSString* columnHeaderCaption;

@property(nonatomic) ASPCellArea* columnRange;

@property(nonatomic) NSNumber* customListSort;

@property(nonatomic) ASPCellArea* dataBodyRange;

@property(nonatomic) ASPPivotPivotField* dataField;

@property(nonatomic) NSArray<ASPPivotPivotField>* dataFields;

@property(nonatomic) NSArray* /* NSString */ dataSource;

@property(nonatomic) NSNumber* displayErrorString;

@property(nonatomic) NSNumber* displayImmediateItems;

@property(nonatomic) NSNumber* displayNullString;

@property(nonatomic) NSNumber* enableDataValueEditing;

@property(nonatomic) NSNumber* enableDrilldown;

@property(nonatomic) NSNumber* enableFieldDialog;

@property(nonatomic) NSNumber* enableFieldList;

@property(nonatomic) NSNumber* enableWizard;

@property(nonatomic) NSString* errorString;

@property(nonatomic) NSNumber* fieldListSortAscending;

@property(nonatomic) NSString* grandTotalName;

@property(nonatomic) NSNumber* hasBlankRows;

@property(nonatomic) NSNumber* indent;

@property(nonatomic) NSNumber* isAutoFormat;

@property(nonatomic) NSNumber* isGridDropZones;

@property(nonatomic) NSNumber* isMultipleFieldFilters;

@property(nonatomic) NSNumber* isSelected;

@property(nonatomic) NSNumber* itemPrintTitles;

@property(nonatomic) NSNumber* manualUpdate;

@property(nonatomic) NSNumber* mergeLabels;

@property(nonatomic) NSString* missingItemsLimit;

@property(nonatomic) NSString* name;

@property(nonatomic) NSString* nullString;

@property(nonatomic) NSString* pageFieldOrder;

@property(nonatomic) NSArray<ASPPivotPivotField>* pageFields;

@property(nonatomic) NSNumber* pageFieldWrapCount;

@property(nonatomic) NSArray<ASPPivotPivotFilter>* pivotFilters;

@property(nonatomic) NSString* pivotTableStyleName;

@property(nonatomic) NSString* pivotTableStyleType;

@property(nonatomic) NSNumber* preserveFormatting;

@property(nonatomic) NSNumber* printDrill;

@property(nonatomic) NSNumber* printTitles;

@property(nonatomic) NSNumber* refreshDataFlag;

@property(nonatomic) NSNumber* refreshDataOnOpeningFile;

@property(nonatomic) NSArray<ASPPivotPivotField>* rowFields;

@property(nonatomic) NSNumber* rowGrand;

@property(nonatomic) NSString* rowHeaderCaption;

@property(nonatomic) ASPCellArea* rowRange;

@property(nonatomic) NSNumber* saveData;

@property(nonatomic) NSNumber* showDataTips;

@property(nonatomic) NSNumber* showDrill;

@property(nonatomic) NSNumber* showEmptyCol;

@property(nonatomic) NSNumber* showEmptyRow;

@property(nonatomic) NSNumber* showMemberPropertyTips;

@property(nonatomic) NSNumber* showPivotStyleColumnHeader;

@property(nonatomic) NSNumber* showPivotStyleColumnStripes;

@property(nonatomic) NSNumber* showPivotStyleLastColumn;

@property(nonatomic) NSNumber* showPivotStyleRowHeader;

@property(nonatomic) NSNumber* showPivotStyleRowStripes;

@property(nonatomic) NSNumber* showRowHeaderCaption;

@property(nonatomic) NSNumber* showValuesRow;

@property(nonatomic) NSNumber* subtotalHiddenPageItems;

@property(nonatomic) ASPCellArea* tableRange1;

@property(nonatomic) ASPCellArea* tableRange2;

@property(nonatomic) NSString* tag;

@property(nonatomic) ASPLink* link;

@end
