#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPSystemObject.h"


@protocol ASPPivotPivotItem
@end

@interface ASPPivotPivotItem : ASPObject


@property(nonatomic) NSNumber* index;

@property(nonatomic) NSNumber* isHidden;

@property(nonatomic) NSString* name;

@property(nonatomic) ASPSystemObject* value;

@end
