#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPLink.h"


@protocol ASPSplitResultDocument
@end

@interface ASPSplitResultDocument : ASPObject


@property(nonatomic) NSNumber* _id;

@property(nonatomic) ASPLink* link;

@end
