#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPSavingSaveOptions
@end

@interface ASPSavingSaveOptions : ASPObject


@property(nonatomic) NSString* cachedFileFolder;

@property(nonatomic) NSNumber* clearData;

@property(nonatomic) NSNumber* createDirectory;

@property(nonatomic) NSNumber* enableHTTPCompression;

@property(nonatomic) NSNumber* refreshChartCache;

@property(nonatomic) NSNumber* sortNames;

@property(nonatomic) NSNumber* validateMergedAreas;

@end
