#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPThemeColor
@end

@interface ASPThemeColor : ASPObject


@property(nonatomic) NSString* colorType;

@property(nonatomic) NSNumber* tint;

@end
