#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPWorkbookSettings
@end

@interface ASPWorkbookSettings : ASPObject


@property(nonatomic) NSNumber* autoCompressPictures;

@property(nonatomic) NSNumber* autoRecover;

@property(nonatomic) NSString* buildVersion;

@property(nonatomic) NSString* calcMode;

@property(nonatomic) NSNumber* calcStackSize;

@property(nonatomic) NSString* calculationId;

@property(nonatomic) NSNumber* checkComptiliblity;

@property(nonatomic) NSNumber* checkExcelRestriction;

@property(nonatomic) NSNumber* crashSave;

@property(nonatomic) NSNumber* createCalcChain;

@property(nonatomic) NSNumber* dataExtractLoad;

@property(nonatomic) NSNumber* date1904;

@property(nonatomic) NSString* displayDrawingObjects;

@property(nonatomic) NSNumber* enableMacros;

@property(nonatomic) NSNumber* firstVisibleTab;

@property(nonatomic) NSNumber* hidePivotFieldList;

@property(nonatomic) NSNumber* isDefaultEncrypted;

@property(nonatomic) NSNumber* isHidden;

@property(nonatomic) NSNumber* isHScrollBarVisible;

@property(nonatomic) NSNumber* isMinimized;

@property(nonatomic) NSNumber* isVScrollBarVisible;

@property(nonatomic) NSNumber* iteration;

@property(nonatomic) NSString* languageCode;

@property(nonatomic) NSNumber* maxChange;

@property(nonatomic) NSNumber* maxIteration;

@property(nonatomic) NSString* memorySetting;

@property(nonatomic) NSString* numberDecimalSeparator;

@property(nonatomic) NSString* numberGroupSeparator;

@property(nonatomic) NSNumber* parsingFormulaOnOpen;

@property(nonatomic) NSNumber* precisionAsDisplayed;

@property(nonatomic) NSNumber* recalculateBeforeSave;

@property(nonatomic) NSNumber* reCalculateOnOpen;

@property(nonatomic) NSNumber* recommendReadOnly;

@property(nonatomic) NSString* region;

@property(nonatomic) NSNumber* removePersonalInformation;

@property(nonatomic) NSNumber* repairLoad;

@property(nonatomic) NSNumber* shared;

@property(nonatomic) NSNumber* sheetTabBarWidth;

@property(nonatomic) NSNumber* showTabs;

@property(nonatomic) NSNumber* updateAdjacentCellsBorder;

@property(nonatomic) NSString* updateLinksType;

@property(nonatomic) NSNumber* windowHeight;

@property(nonatomic) NSNumber* windowLeft;

@property(nonatomic) NSNumber* windowTop;

@property(nonatomic) NSNumber* windowWidth;

@end
