#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPColor.h"


@protocol ASPBorder
@end

@interface ASPBorder : ASPObject


@property(nonatomic) NSString* lineStyle;

@property(nonatomic) ASPColor* color;

@property(nonatomic) NSString* borderType;

@end
