#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPLink.h"
#import "ASPCellsDocumentProperty.h"


@protocol ASPCellsDocumentProperties
@end

@interface ASPCellsDocumentProperties : ASPObject


@property(nonatomic) NSArray<ASPCellsDocumentProperty>* documentPropertyList;

@property(nonatomic) ASPLink* link;

@end
