#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPCellsDocumentProperties.h"


@protocol ASPCellsDocumentPropertiesResponse
@end

@interface ASPCellsDocumentPropertiesResponse : ASPObject


@property(nonatomic) ASPCellsDocumentProperties* documentProperties;

@property(nonatomic) NSString* code;

@property(nonatomic) NSString* status;

@end
