#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPCellArea
@end

@interface ASPCellArea : ASPObject


@property(nonatomic) NSNumber* endColumn;

@property(nonatomic) NSNumber* endRow;

@property(nonatomic) NSNumber* startColumn;

@property(nonatomic) NSNumber* startRow;

@end
