#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPCellsColor.h"
#import "ASPColor.h"


@protocol ASPDrawingSolidFill
@end

@interface ASPDrawingSolidFill : ASPObject


@property(nonatomic) ASPColor* color;

@property(nonatomic) ASPCellsColor* cellsColor;

@property(nonatomic) NSNumber* transparency;

@end
