#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPDrawingGradientFillStop.h"


@protocol ASPDrawingGradientFill
@end

@interface ASPDrawingGradientFill : ASPObject


@property(nonatomic) NSString* fillType;

@property(nonatomic) NSString* directionType;

@property(nonatomic) NSNumber* angle;

@property(nonatomic) NSArray<ASPDrawingGradientFillStop>* gradientStops;

@end
