#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPDateTimeGroupItem
@end

@interface ASPDateTimeGroupItem : ASPObject


@property(nonatomic) NSString* dateTimeGroupingType;

@property(nonatomic) NSNumber* day;

@property(nonatomic) NSNumber* hour;

@property(nonatomic) NSNumber* minute;

@property(nonatomic) NSNumber* month;

@property(nonatomic) NSNumber* second;

@property(nonatomic) NSNumber* year;

@end
