#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPColor.h"
#import "ASPDrawingGradientFill.h"


@protocol ASPDrawingLine
@end

@interface ASPDrawingLine : ASPObject


@property(nonatomic) NSString* beginArrowLength;

@property(nonatomic) NSString* beginArrowWidth;

@property(nonatomic) NSString* beginType;

@property(nonatomic) NSString* capType;

@property(nonatomic) ASPColor* color;

@property(nonatomic) NSString* compoundType;

@property(nonatomic) NSString* dashType;

@property(nonatomic) NSString* endArrowLength;

@property(nonatomic) NSString* endArrowWidth;

@property(nonatomic) NSString* endType;

@property(nonatomic) ASPDrawingGradientFill* gradientFill;

@property(nonatomic) NSNumber* isAuto;

@property(nonatomic) NSNumber* isAutomaticColor;

@property(nonatomic) NSNumber* isVisible;

@property(nonatomic) NSString* joinType;

@property(nonatomic) NSString* style;

@property(nonatomic) NSNumber* transparency;

@property(nonatomic) NSString* weight;

@property(nonatomic) NSNumber* weightPt;

@end
