#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPDrawingPicFormatOption
@end

@interface ASPDrawingPicFormatOption : ASPObject


@property(nonatomic) NSString* type;

@property(nonatomic) NSNumber* scale;

@property(nonatomic) NSNumber* left;

@property(nonatomic) NSNumber* right;

@property(nonatomic) NSNumber* top;

@property(nonatomic) NSNumber* bottom;

@end
