#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPSystemObject.h"


@protocol ASPDynamicFilter
@end

@interface ASPDynamicFilter : ASPObject


@property(nonatomic) NSString* dynamicFilterType;

@property(nonatomic) ASPSystemObject* maxValue;

@property(nonatomic) ASPSystemObject* value;

@end
