#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPLink.h"


@protocol ASPDrawingOleObject
@end

@interface ASPDrawingOleObject : ASPObject


@property(nonatomic) NSNumber* displayAsIcon;

@property(nonatomic) NSString* fileFormatType;

@property(nonatomic) NSString* imageSourceFullName;

@property(nonatomic) NSNumber* isAutoSize;

@property(nonatomic) NSNumber* isLink;

@property(nonatomic) NSString* progID;

@property(nonatomic) NSString* sourceFullName;

@property(nonatomic) NSString* name;

@property(nonatomic) NSString* msoDrawingType;

@property(nonatomic) NSString* autoShapeType;

@property(nonatomic) NSString* placement;

@property(nonatomic) NSNumber* upperLeftRow;

@property(nonatomic) NSNumber* top;

@property(nonatomic) NSNumber* upperLeftColumn;

@property(nonatomic) NSNumber* left;

@property(nonatomic) NSNumber* lowerRightRow;

@property(nonatomic) NSNumber* bottom;

@property(nonatomic) NSNumber* lowerRightColumn;

@property(nonatomic) NSNumber* right;

@property(nonatomic) NSNumber* width;

@property(nonatomic) NSNumber* height;

@property(nonatomic) NSNumber* X;

@property(nonatomic) NSNumber* Y;

@property(nonatomic) NSNumber* rotationAngle;

@property(nonatomic) NSString* htmlText;

@property(nonatomic) NSString* text;

@property(nonatomic) NSString* alternativeText;

@property(nonatomic) NSString* textHorizontalAlignment;

@property(nonatomic) NSString* textHorizontalOverflow;

@property(nonatomic) NSString* textOrientationType;

@property(nonatomic) NSString* textVerticalAlignment;

@property(nonatomic) NSString* textVerticalOverflow;

@property(nonatomic) NSNumber* isGroup;

@property(nonatomic) NSNumber* isHidden;

@property(nonatomic) NSNumber* isLockAspectRatio;

@property(nonatomic) NSNumber* isLocked;

@property(nonatomic) NSNumber* isPrintable;

@property(nonatomic) NSNumber* isTextWrapped;

@property(nonatomic) NSNumber* isWordArt;

@property(nonatomic) NSString* linkedCell;

@property(nonatomic) NSNumber* zOrderPosition;

@property(nonatomic) ASPLink* link;

@end
