#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPName.h"


@protocol ASPNameResponse
@end

@interface ASPNameResponse : ASPObject


@property(nonatomic) ASPName* name;

@property(nonatomic) NSString* code;

@property(nonatomic) NSString* status;

@end
