#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPProtectSheetParameter
@end

@interface ASPProtectSheetParameter : ASPObject


@property(nonatomic) NSString* protectionType;

@property(nonatomic) NSString* password;

@property(nonatomic) NSArray* /* NSString */ allowEditArea;

@property(nonatomic) NSString* allowDeletingColumn;

@property(nonatomic) NSString* allowDeletingRow;

@property(nonatomic) NSString* allowFiltering;

@property(nonatomic) NSString* allowFormattingCell;

@property(nonatomic) NSString* allowFormattingColumn;

@property(nonatomic) NSString* allowFormattingRow;

@property(nonatomic) NSString* allowInsertingColumn;

@property(nonatomic) NSString* allowInsertingHyperlink;

@property(nonatomic) NSString* allowInsertingRow;

@property(nonatomic) NSString* allowSelectingLockedCell;

@property(nonatomic) NSString* allowSelectingUnlockedCell;

@property(nonatomic) NSString* allowSorting;

@property(nonatomic) NSString* allowUsingPivotTable;

@end
