#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPFont.h"
#import "ASPBorder.h"
#import "ASPLink.h"
#import "ASPColor.h"


@protocol ASPStyle
@end

@interface ASPStyle : ASPObject


@property(nonatomic) ASPFont* font;

@property(nonatomic) NSString* name;

@property(nonatomic) NSString* cultureCustom;

@property(nonatomic) NSString* custom;

@property(nonatomic) ASPColor* backgroundColor;

@property(nonatomic) ASPColor* foregroundColor;

@property(nonatomic) NSNumber* isFormulaHidden;

@property(nonatomic) NSNumber* isDateTime;

@property(nonatomic) NSNumber* isTextWrapped;

@property(nonatomic) NSNumber* isGradient;

@property(nonatomic) NSNumber* isLocked;

@property(nonatomic) NSNumber* isPercent;

@property(nonatomic) NSNumber* shrinkToFit;

@property(nonatomic) NSNumber* indentLevel;

@property(nonatomic) NSNumber* number;

@property(nonatomic) NSNumber* rotationAngle;

@property(nonatomic) NSString* pattern;

@property(nonatomic) NSString* textDirection;

@property(nonatomic) NSString* verticalAlignment;

@property(nonatomic) NSString* horizontalAlignment;

@property(nonatomic) NSArray<ASPBorder>* borderCollection;

@property(nonatomic) ASPLink* link;

@end
