#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPTop10Filter
@end

@interface ASPTop10Filter : ASPObject


@property(nonatomic) NSString* criteria;

@property(nonatomic) NSString* isPercent;

@property(nonatomic) NSString* isTop;

@property(nonatomic) NSNumber* items;

@end
