#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPLinkElement.h"


@protocol ASPWorksheetReplaceResponse
@end

@interface ASPWorksheetReplaceResponse : ASPObject


@property(nonatomic) NSNumber* matches;

@property(nonatomic) ASPLinkElement* worksheet;

@property(nonatomic) NSString* code;

@property(nonatomic) NSString* status;

@end
