#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPLink.h"
#import "ASPLinkElement.h"


@protocol ASPWorkbook
@end

@interface ASPWorkbook : ASPObject


@property(nonatomic) NSString* fileName;

@property(nonatomic) NSArray<ASPLink>* links;

@property(nonatomic) ASPLinkElement* worksheets;

@property(nonatomic) ASPLinkElement* defaultStyle;

@property(nonatomic) ASPLinkElement* documentProperties;

@property(nonatomic) ASPLinkElement* names;

@property(nonatomic) ASPLinkElement* settings;

@property(nonatomic) NSString* isWriteProtected;

@property(nonatomic) NSString* isProtected;

@property(nonatomic) NSString* isEncryption;

@property(nonatomic) NSString* password;

@end
