require 'aspose_storage_cloud'

# Common files
require_relative 'aspose_cells_cloud/version'
require_relative 'aspose_cells_cloud/configuration'
require_relative 'aspose_cells_cloud/api_client'
require_relative 'aspose_cells_cloud/api_error'

# Models
require_relative 'aspose_cells_cloud/models/base_object'
require_relative 'aspose_cells_cloud/models/pictures_response'
require_relative 'aspose_cells_cloud/models/drawing_pictures'
require_relative 'aspose_cells_cloud/models/link_element'
require_relative 'aspose_cells_cloud/models/link'
require_relative 'aspose_cells_cloud/models/drawing_picture'
require_relative 'aspose_cells_cloud/models/color'
require_relative 'aspose_cells_cloud/models/picture_response'
require_relative 'aspose_cells_cloud/models/workbook_response'
require_relative 'aspose_cells_cloud/models/workbook'
require_relative 'aspose_cells_cloud/models/workbook_encryption_request'
require_relative 'aspose_cells_cloud/models/workbook_protection_request'
require_relative 'aspose_cells_cloud/models/style_response'
require_relative 'aspose_cells_cloud/models/style'
require_relative 'aspose_cells_cloud/models/font'
require_relative 'aspose_cells_cloud/models/border'
require_relative 'aspose_cells_cloud/models/text_items_response'
require_relative 'aspose_cells_cloud/models/text_items'
require_relative 'aspose_cells_cloud/models/text_item'
require_relative 'aspose_cells_cloud/models/names_response'
require_relative 'aspose_cells_cloud/models/names'
require_relative 'aspose_cells_cloud/models/name_response'
require_relative 'aspose_cells_cloud/models/name'
require_relative 'aspose_cells_cloud/models/password_request'
require_relative 'aspose_cells_cloud/models/workbook_replace_response'
require_relative 'aspose_cells_cloud/models/split_result_response'
require_relative 'aspose_cells_cloud/models/split_result'
require_relative 'aspose_cells_cloud/models/split_result_document'
require_relative 'aspose_cells_cloud/models/import_data_import_option'
require_relative 'aspose_cells_cloud/models/auto_fitter_options'
require_relative 'aspose_cells_cloud/models/workbook_settings_response'
require_relative 'aspose_cells_cloud/models/workbook_settings'
require_relative 'aspose_cells_cloud/models/validations_response'
require_relative 'aspose_cells_cloud/models/validations'
require_relative 'aspose_cells_cloud/models/validation_response'
require_relative 'aspose_cells_cloud/models/validation'
require_relative 'aspose_cells_cloud/models/cell_area'
require_relative 'aspose_cells_cloud/models/cells_document_properties_response'
require_relative 'aspose_cells_cloud/models/cells_document_properties'
require_relative 'aspose_cells_cloud/models/cells_document_property'
require_relative 'aspose_cells_cloud/models/cells_document_property_response'
require_relative 'aspose_cells_cloud/models/pivot_tables_response'
require_relative 'aspose_cells_cloud/models/pivot_pivot_tables'
require_relative 'aspose_cells_cloud/models/create_pivot_table_request'
require_relative 'aspose_cells_cloud/models/pivot_table_response'
require_relative 'aspose_cells_cloud/models/pivot_pivot_table'
require_relative 'aspose_cells_cloud/models/pivot_pivot_field'
require_relative 'aspose_cells_cloud/models/pivot_pivot_filter'
require_relative 'aspose_cells_cloud/models/pivot_pivot_item'
require_relative 'aspose_cells_cloud/models/auto_filter'
require_relative 'aspose_cells_cloud/models/filter_column'
require_relative 'aspose_cells_cloud/models/data_sorter'
require_relative 'aspose_cells_cloud/models/multiple_filters'
require_relative 'aspose_cells_cloud/models/color_filter'
require_relative 'aspose_cells_cloud/models/custom_filter'
require_relative 'aspose_cells_cloud/models/dynamic_filter'
require_relative 'aspose_cells_cloud/models/icon_filter'
require_relative 'aspose_cells_cloud/models/top10_filter'
require_relative 'aspose_cells_cloud/models/sort_key'
require_relative 'aspose_cells_cloud/models/date_time_group_item'
require_relative 'aspose_cells_cloud/models/pivot_field_response'
require_relative 'aspose_cells_cloud/models/pivot_table_field_request'
require_relative 'aspose_cells_cloud/models/chart_area_response'
require_relative 'aspose_cells_cloud/models/charts_chart_area'
require_relative 'aspose_cells_cloud/models/drawing_area'
require_relative 'aspose_cells_cloud/models/drawing_line'
require_relative 'aspose_cells_cloud/models/drawing_fill_format'
require_relative 'aspose_cells_cloud/models/drawing_gradient_fill'
require_relative 'aspose_cells_cloud/models/drawing_solid_fill'
require_relative 'aspose_cells_cloud/models/drawing_pattern_fill'
require_relative 'aspose_cells_cloud/models/drawing_texture_fill'
require_relative 'aspose_cells_cloud/models/drawing_gradient_fill_stop'
require_relative 'aspose_cells_cloud/models/cells_color'
require_relative 'aspose_cells_cloud/models/drawing_tile_pic_option'
require_relative 'aspose_cells_cloud/models/drawing_pic_format_option'
require_relative 'aspose_cells_cloud/models/theme_color'
require_relative 'aspose_cells_cloud/models/fill_format_response'
require_relative 'aspose_cells_cloud/models/line_response'
require_relative 'aspose_cells_cloud/models/columns_response'
require_relative 'aspose_cells_cloud/models/columns'
require_relative 'aspose_cells_cloud/models/column_response'
require_relative 'aspose_cells_cloud/models/column'
require_relative 'aspose_cells_cloud/models/cells_response'
require_relative 'aspose_cells_cloud/models/cells'
require_relative 'aspose_cells_cloud/models/cell_response'
require_relative 'aspose_cells_cloud/models/cell'
require_relative 'aspose_cells_cloud/models/rows_response'
require_relative 'aspose_cells_cloud/models/rows'
require_relative 'aspose_cells_cloud/models/row_response'
require_relative 'aspose_cells_cloud/models/row'
require_relative 'aspose_cells_cloud/models/worksheets_response'
require_relative 'aspose_cells_cloud/models/worksheets'
require_relative 'aspose_cells_cloud/models/worksheet'
require_relative 'aspose_cells_cloud/models/worksheet_response'
require_relative 'aspose_cells_cloud/models/worksheet_moving_request'
require_relative 'aspose_cells_cloud/models/protect_sheet_parameter'
require_relative 'aspose_cells_cloud/models/comments_response'
require_relative 'aspose_cells_cloud/models/comments'
require_relative 'aspose_cells_cloud/models/comment_response'
require_relative 'aspose_cells_cloud/models/comment'
require_relative 'aspose_cells_cloud/models/merged_cells_response'
require_relative 'aspose_cells_cloud/models/merged_cells'
require_relative 'aspose_cells_cloud/models/merged_cell_response'
require_relative 'aspose_cells_cloud/models/merged_cell'
require_relative 'aspose_cells_cloud/models/single_value_response'
require_relative 'aspose_cells_cloud/models/single_value'
require_relative 'aspose_cells_cloud/models/worksheet_replace_response'
require_relative 'aspose_cells_cloud/models/ole_objects_response'
require_relative 'aspose_cells_cloud/models/drawing_ole_objects'
require_relative 'aspose_cells_cloud/models/drawing_ole_object'
require_relative 'aspose_cells_cloud/models/ole_object_response'
require_relative 'aspose_cells_cloud/models/auto_shapes_response'
require_relative 'aspose_cells_cloud/models/drawing_auto_shapes'
require_relative 'aspose_cells_cloud/models/auto_shape_response'
require_relative 'aspose_cells_cloud/models/saving_save_options'
require_relative 'aspose_cells_cloud/models/save_response'
require_relative 'aspose_cells_cloud/models/save_result'
require_relative 'aspose_cells_cloud/models/hyperlinks_response'
require_relative 'aspose_cells_cloud/models/hyperlinks'
require_relative 'aspose_cells_cloud/models/hyperlink_response'
require_relative 'aspose_cells_cloud/models/hyperlink'
require_relative 'aspose_cells_cloud/models/charts_response'
require_relative 'aspose_cells_cloud/models/charts_charts'
require_relative 'aspose_cells_cloud/models/legend_response'
require_relative 'aspose_cells_cloud/models/charts_legend'
require_relative 'aspose_cells_cloud/models/charts_title'
require_relative 'aspose_cells_cloud/models/title_response'
require_relative 'aspose_cells_cloud/models/base_response'
require_relative 'aspose_cells_cloud/models/barcode_response_list'
require_relative 'aspose_cells_cloud/models/barcode_response'

# APIs
require_relative 'aspose_cells_cloud/api/cells_api'

module AsposeCellsCloud
  class << self
    # Configure sdk using block.
    # AsposeCellsCloud.configure do |config|
    #   config.username = "xxx"
    #   config.password = "xxx"
    # end
    # If no block given, return the configuration singleton instance.
    
    def configure
      if block_given?
        yield Configuration.instance
      else
        Configuration.instance
      end
    end
  end
end
